AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/CaseIndentation:
  EnforcedStyle: end

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
